[build]
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://nordlysmap.com"
  NEXT_PUBLIC_DOMAIN = "nordlysmap.com"

# Redirect rules for custom domain
[[redirects]]
  from = "https://www.nordlysmap.com/*"
  to = "https://nordlysmap.com/:splat"
  status = 301
  force = true
